---
- name: Setting up interfaces
  hosts: all
  become: yes
  tasks:
    - name: Configure interface with static IP
      ansible.builtin.copy:
        dest: /etc/network/interfaces.d/{{ inventory_hostname }}.cfg
        content: |
          auto {{ interface }}
          iface {{ interface }} inet static
          address {{ interface_ip }}
          netmask 255.255.255.0
          gateway 192.168.1.1

- name: Deploy and Configure ISC DHCP Server
  hosts: head-node
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade all packages to the latest version
      apt:
        upgrade: dist

    - name: Install ISC DHCP Server
      apt:
        name: isc-dhcp-server
        state: present

    - name: Configure DHCP Server
      template:
        src: conf.d/dhcpd.conf.j2
        dest: /etc/dhcp/dhcpd.conf
        owner: root
        group: root
        mode: '0644'

    - name: Configure ISC-DHCP Default
      template:
        src: conf.d/isc-dhcp-server.j2
        dest: /etc/default/isc-dhcp-server
        owner: root
        group: root
        mode: '0644'
        
    - name: System Control
      template:
        src: conf.d/sysctl.conf.j2
        dest: /etc/sysctl.conf
        owner: root
        group: root
        mode: '0644'

    - name: Apply ip forwarding
      command: sysctl -p

- name: Setup iptables rules
  hosts: head-node
  become: yes
  tasks:
    - name: Install iptables-persistent
      apt:
        name: iptables-persistent
        state: present
        update_cache: yes

    - name: Set NAT POSTROUTING rule
      command: iptables -t nat -A POSTROUTING -o {{ interface_out }} -j MASQUERADE

    - name: Allow forwarded traffic related and established connections
      command: iptables -A FORWARD -i {{ interface }} -o {{ interface_out}} -m state --state RELATED,ESTABLISHED -j ACCEPT

    - name: Allow forwarded traffic from {{ interface_out}} to wlan0
      command: iptables -A FORWARD -i {{ interface_out}} -o {{ interface }} -j ACCEPT

    - name: Save iptables rules
      shell: iptables-save > /etc/iptables/rules.v4

    - name: Ensure iptables-persistent service is enabled and started
      systemd:
        name: netfilter-persistent
        enabled: yes
        state: started

- name: Restart networking
  hosts: all
  become: yes
  tasks:
    - name: Reboot the machine
      reboot:
        reboot_timeout: 600
      ignore_errors: true