- hosts: all
  any_errors_fatal: true
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Update hostname
      hostname:
        name: "{{ inventory_hostname }}"

    - name: Copy /etc/hosts files from localhost to hosts
      ansible.builtin.copy:
        src: ./configs/hosts
        dest: /etc/hosts
        owner: root
        group: root
        mode: '0644'

    - name: Enable the hostname
      command: hostnamectl set-hostname {{ inventory_hostname }}