- name: Mount NFS direcoty on all compute nodes
  hosts: compute_nodes
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install NFS kernel package
      ansible.builtin.package:
        name: nfs-common
        state: present

    - name: Mount home directory
      command: mount {{ nfs_host }}:/home /home
