---
- name: Install required packages for building Debian packages
  hosts: all
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install htop
      apt:
        name: htop
        state: present

    - name: Install build-essential
      apt:
        name: build-essential
        state: present

    - name: Install fakeroot
      apt:
        name: fakeroot
        state: present

    - name: Install devscripts
      apt:
        name: devscripts
        state: present

    - name: Install equivs
      apt:
        name: equivs
        state: present

- name: Download and build Slurm Debian packages
  hosts: head_node
  become: yes
  tasks:
    - name: Get {{ slurm_url }}
      get_url:
        url: "{{ slurm_url }}"
        dest: "/tmp/{{ slurm_version }}.tar.bz2"

    - name: Unpack the distributed tarball
      ansible.builtin.unarchive:
        src: /tmp/{{ slurm_version }}.tar.bz2
        dest: /tmp/
        remote_src: yes

    - name: Make building dependencies
      ansible.builtin.shell: yes | mk-build-deps -i debian/control
      args:
        chdir: /tmp/{{ slurm_version }}

    - name: Build the Slurm packages
      ansible.builtin.shell: debuild -b -uc -us
      args:
        chdir: /tmp/{{ slurm_version }}

    - name: Move the built packages to a specified directory
      ansible.builtin.command:
        cmd: mv /tmp/*.deb ~/{{ slurm_version }}