---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Debug extracted variables
      debug:
        msg:
          - "Slurm URL: {{ slurm_url }}"
          - "Slurm Version: {{ slurm_version }}"
          - "Slurm Filename: {{ slurm_filename }}"

- hosts: localhost
  gather_facts: false
  vars_prompt:
    - name: user_confirmation
      prompt: "Are these variables correct? Type 'yes' to proceed.\nAnswer"
      private: no
  tasks:
    - name: Stop process if user does not confirm
      ansible.builtin.fail:
        msg: "Canceling process because the variables were not confirmed."
      when: user_confirmation != 'yes'

- hosts: all
  gather_facts: yes
  any_errors_fatal: true
  become: yes
  tasks:
    - name: Setup the slurm-smd
      ansible.builtin.shell:
        cmd: apt install -y ./slurm-smd_{{ slurm_version }}_amd64.deb
      args:
        chdir: /home/slurm

- hosts: head_node,compute_nodes,login_node
  gather_facts: yes
  any_errors_fatal: true
  become: yes
  tasks:
    - name: Setup the slurm-smd-client
      ansible.builtin.shell:
        cmd: apt install -y ./slurm-smd-client_{{ slurm_version }}_amd64.deb
      args:
        chdir: /home/slurm

- hosts: head_node
  gather_facts: yes
  any_errors_fatal: true
  become: yes
  tasks:
    - name: Setup the slurm-smd-slurmctld
      ansible.builtin.shell:
        cmd: apt install -y ./slurm-smd-slurmctld_{{ slurm_version }}_amd64.deb
      args:
        chdir: /home/slurm

    - name: Enable slurmctld
      ansible.builtin.shell:
        cmd: systemctl enable slurmctld
      args:
        chdir: /home/slurm

- hosts: compute_nodes
  gather_facts: yes
  any_errors_fatal: true
  become: yes
  tasks:
    - name: Setup the slurm-smd-slurmd
      ansible.builtin.shell:
        cmd: apt install -y ./slurm-smd-slurmd_{{ slurm_version }}_amd64.deb
      args:
        chdir: /home/slurm

    - name: Enable slurmd
      ansible.builtin.shell:
        cmd: systemctl enable slurmd
      args:
        chdir: /home/slurm

- hosts: db_node
  gather_facts: yes
  any_errors_fatal: true
  become: yes
  tasks:
    - name: Setup the slurm-smd-slurmdbd	
      ansible.builtin.shell:
        cmd: apt install -y ./slurm-smd-slurmdbd_{{ slurm_version }}_amd64.deb
      args:
        chdir: /home/slurm

    - name: Enable slurmdbd
      ansible.builtin.shell:
        cmd: systemctl enable slurmdbd
      args:
        chdir: /home/slurm
