---
- hosts: all
  gather_facts: true
  any_errors_fatal: true
  become: yes
  tasks:
    - name: Ensure correct timezone is set
      timezone:
        name: "Asia/Taipei"

    - name: Install NTP package
      ansible.builtin.package:
        name: ntp
        state: present
    
    - name: Install NTPDate
      apt:
        name: ntpdate
        state: present

    - name: Adjust datetime
      ansible.builtin.shell:
        cmd: ntpdate TIME.google.com

    - name: Update and upgrade apt packages
      become: true
      apt:
        update_cache: yes
        upgrade: yes