---
- name: Install required packages for building Debian packages
  hosts: all
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install build-essential
      apt:
        name: build-essential
        state: present

    - name: Install fakeroot
      apt:
        name: fakeroot
        state: present

    - name: Install devscripts
      apt:
        name: devscripts
        state: present

    - name: Install equivs
      apt:
        name: equivs
        state: present

    - name: Install distcc
      apt:
        name: distcc
        state: present

    - name: Check if distccd is running
      command: pgrep -f distccd
      register: distccd_status
      ignore_errors: yes

    - name: Stop distccd daemon if running
      command: pkill -f distccd
      when: distccd_status.rc == 0

    - name: Start distccd
      command: distccd --daemon --allow "{{ network }}"
